---
songs:
  - song: "One Headlight"
    artist: "The Wallflowers"
  - song: "Scotty Doesn't Know"
    artist: "Lustra"
  - song: "Welcome to the Jungle"
    artist: "Guns N' Roses"
  - song: "Kiss Me"
    artist: "Sixpence None the Richer"
  - song: "Hotel California"
    artist: "Eagles"
  - song: "Woman"
    artist: "Wolfmother"
  - song: "The Joker"
    artist: "Steve Miller Band"
  - song: "I Believe In A Thing Called Love"
    artist: "The Darkness"
  - song: "Seven Bridges Road"
    artist: "Eagles"
